export const SELECT_HARMONIC = 'SELECT_HARMONIC';
export type SELECT_HARMONIC = typeof SELECT_HARMONIC;

export const ADD_HARMONIC = 'ADD_HARMONIC';
export type ADD_HARMONIC = typeof ADD_HARMONIC;

export const DELETE_HARMONIC = 'DELETE_HARMONIC';
export type DELETE_HARMONIC = typeof DELETE_HARMONIC;

export const TOGGLE_ADD_DIALOG = 'TOGGLE_ADD_DIALOG';
export type TOGGLE_ADD_DIALOG = typeof TOGGLE_ADD_DIALOG;

export const ADD_HARMONIC_CHANGE = 'ADD_HARMONIC_CHANGE';
export type ADD_HARMONIC_CHANGE = typeof ADD_HARMONIC_CHANGE;